[build]
publish = "build"
command = "bash scripts/sync-techdocs-docs.sh && npm ci && npm run build:preview"

[context.production]
command = "bash scripts/sync-techdocs-docs.sh && npm ci && npm run build:production"
